### ISSUE TITLE
task_page.php returns wrong Descriptions

### ISSUE THREAD

**Issue by lberning** [mantisbt-plugins/agileMantis#2]
While trying agileMantis with our MantisBT-Installation I noticed that I had wrong Descriptions/ Steps To Reproduce and Additional Information for my Issues when going to the "Add Task" Page.

Digging a bit deeper I think the getUserStoryById in "class_commonlib.php" does the join on the wrong index, it should be: "ON btt.id=bt.bug_text_id" instead of ON "btt.id=bt.id"

**Comment by jazsch** [comment]
Hi,
could this change you proposed fix your problem?
These both ids are mostly the same, I think this is why this index was used.
Thank you for your information.

Best regards Janine Zschörner

**Comment by lberning** [comment]
Hi Janine,
thanks for the reply. Yes, that little change totally fixed the problem for me. I guess normally you would have both db tables with exactly the same number of entries so you wouldn't notice a difference with the indexes.
Our MantisBT installation is in production use for approx. 10 years, migrated from update to update so I  guess that something might have caused the tables to not run coincidently in sync...

**Comment by jazsch** [comment]
Hi,
I recorded this adjustment for the next version.
Thanks for your further explantation. This is really understandable.
