### ISSUE TITLE
[Q] Does agileMantis support management of epics? 

### ISSUE THREAD

**Issue by leledumbo** [mantisbt-plugins/agileMantis#4]
From quick glance after installation, I don't see it's directly supported. But I just want to know if there's any way to make it available in the current installation before I proceed with my own modification.

**Comment by jazsch** [comment]
Hi,
What do you mean exactly with epics?

Best regards
Janine Zschörner

**Comment by leledumbo** [comment]
http://scrummethodology.com/scrum-epics/

Just as sprint groups stories to be done by time, epics group stories by purpose. e.g.: product management epic may consist of product creation, product read, product update and product deletion stories (standard CRUD). They may be executed in one or more sprints, however.

**Comment by jazsch** [comment]
Hi,

in agileMantis you could split incomplete user stories at the end of a sprint and could adopt them in the next sprint.
You are not able to group stories and show this group in the sprint backlog.

Could these information help you?

Best regards
Janine Zschörner

**Comment by leledumbo** [comment]
I conclude that as "epic is not supported" under current implementation. Very well, I'll get my hands dirty on it. Thanks for the information.
